"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const ProductController_js_1 = require("../controllers/ProductController.js");
const router = (0, express_1.Router)();
const productController = new ProductController_js_1.ProductController();
router.get("/", productController.getAll);
router.get("/:id", productController.getById);
router.post("/", productController.create);
router.put("/:id", productController.update);
router.delete("/:id", productController.delete);
exports.default = router;
